export const ROLES = {
  ADMIN_FULL: 'admin_full',
  // Backwards-compatible alias for older code referencing ROLES.ADMIN
  ADMIN: 'admin_full',
  ADMIN_APPROVAL: 'admin_approval', 
  OFFICER: 'officer',
  VIEWER: 'viewer',
};

export const PERMISSIONS = {
  CAN_VIEW_TRANSPARENCY: 'view_transparency',
  CAN_UPLOAD_FILES: 'upload_files',
  CAN_MANAGE_CONTENT: 'manage_content',
  CAN_APPROVE_FILES: 'approve_files',
  CAN_REVIEW_SUBMISSIONS: 'review_submissions',
  CAN_MONITOR_ACTIVITIES: 'monitor_activities',
  CAN_MANAGE_USERS: 'manage_users',
  CAN_MANAGE_ORGANIZATIONS: 'manage_organizations',
  CAN_MANAGE_SYSTEM_SETTINGS: 'manage_system_settings',
  CAN_VIEW_ANALYTICS: 'view_analytics',
};

export const ROLE_PERMISSIONS = {
  [ROLES.ADMIN_FULL]: [
    PERMISSIONS.CAN_VIEW_TRANSPARENCY,
    PERMISSIONS.CAN_UPLOAD_FILES,
    PERMISSIONS.CAN_MANAGE_CONTENT,
    PERMISSIONS.CAN_APPROVE_FILES,
    PERMISSIONS.CAN_REVIEW_SUBMISSIONS,
    PERMISSIONS.CAN_MONITOR_ACTIVITIES,
    PERMISSIONS.CAN_MANAGE_USERS,
    PERMISSIONS.CAN_MANAGE_ORGANIZATIONS,
    PERMISSIONS.CAN_MANAGE_SYSTEM_SETTINGS,
    PERMISSIONS.CAN_VIEW_ANALYTICS,
  ],
  [ROLES.ADMIN_APPROVAL]: [
    PERMISSIONS.CAN_VIEW_TRANSPARENCY,
    PERMISSIONS.CAN_APPROVE_FILES,
    PERMISSIONS.CAN_REVIEW_SUBMISSIONS,
    PERMISSIONS.CAN_MONITOR_ACTIVITIES,
    PERMISSIONS.CAN_MANAGE_CONTENT,
  ],
  [ROLES.OFFICER]: [
    PERMISSIONS.CAN_VIEW_TRANSPARENCY,
    PERMISSIONS.CAN_UPLOAD_FILES,
    PERMISSIONS.CAN_MANAGE_CONTENT,
  ],
  [ROLES.VIEWER]: [PERMISSIONS.CAN_VIEW_TRANSPARENCY],
};
